import javax.swing.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author usuario
 */
public class interfaz_lista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfaz_lista.class.getName());

    /**
     * Creates new form interfaz_lista
     */
    public interfaz_lista() {
        initComponents();
        gestor_de_tareas g = new gestor_de_tareas();
        g.setTareas();
        ModeloTablaPrio prio = new ModeloTablaPrio(g.getTareas());
        tabla.setModel(prio.getModelo());
        tabla.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "eliminarFila");
        tabla.getActionMap().put("eliminarFila", new AbstractAction() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        try {
                            eliminar();
                        } catch (IOException ex) {
                            throw new RuntimeException(ex);
                        }
                    }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable(); // CAMBIADO: De JList a JTable
        cmbOrden = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tablaMouseClicked(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {

        });
        jScrollPane1.setViewportView(tabla);

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioridad", "Fecha", "Alfabéticamente" }));
        cmbOrden.addActionListener(this::cmbOrdenActionPerformed);

        btnCrear.setText("Crear Nueva");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        jLabel1.setText("Ordenar:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrear)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir)
                                .addContainerGap(107, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCrear, btnSalir, cmbOrden, jLabel1});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(75, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrear)
                                        .addComponent(btnSalir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCrear, btnSalir, cmbOrden, jLabel1});

        pack();
        setLocationRelativeTo(null);

    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        crear_tarea c = new crear_tarea();
        dispose();
        c.setVisible(true);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_tablaMouseClicked
        gestor_de_tareas g = new gestor_de_tareas();
        g.setTareas();
        ArrayList<Tarea> tareas = g.getTareas();
        if (evt.getClickCount() == 2) {
            int fila = tabla.getSelectedRow();
            String titulo = tabla.getModel().getValueAt(fila, 0).toString();
            int opcion=JOptionPane.showConfirmDialog(null, "Quieres editar la tarea?");
            if (opcion == JOptionPane.YES_OPTION) {
                for (Tarea tarea : tareas){
                    if (tarea.getTitulo().equals(titulo)){
                        tarea.editarTarea(tarea);
                    }
                }
            }


        }

    }//GEN-LAST:event_tablaMouseClicked
    private void eliminar() throws IOException {
            gestor_de_tareas g = new gestor_de_tareas();
            g.setTareas();
            ArrayList<Tarea> tareas = g.getTareas();
            int fila = tabla.getSelectedRow();
            String titular = tabla.getModel().getValueAt(fila, 0).toString();
            int option =JOptionPane.showConfirmDialog(null, "Quieres eliminar la tarea?");
            if(option ==0){
                for (Tarea tarea : tareas) {
                    if (tarea.getTitulo().equals(titular)) {
                        tarea.eliminarDirectorio(new File(tarea.getArchivo().getParent() + "/"));
                        JOptionPane.showMessageDialog(null, "Tarea eliminada.");
                    }
                }
                g.setTareas();
                if(cmbOrden.getSelectedIndex() == 0){
                    ModeloTablaPrio prio = new ModeloTablaPrio(g.getTareas());
                    tabla.setModel(prio.getModelo());
                }
                if (cmbOrden.getSelectedIndex() == 1){
                    ModeloTablaFecha fecha = new ModeloTablaFecha(g.getTareas());
                    tabla.setModel(fecha.getModelo());
                }
                if (cmbOrden.getSelectedIndex() == 2){
                    ModeloTablaAlf alf = new ModeloTablaAlf(g.getTareas());
                    tabla.setModel(alf.getModelo());
                }

            } else{
                JOptionPane.showMessageDialog(null, "Cancelado");

            }


    }

    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
        gestor_de_tareas g = new gestor_de_tareas();
        g.setTareas();
        if(cmbOrden.getSelectedIndex() == 0){
            ModeloTablaPrio prio = new ModeloTablaPrio(g.getTareas());
            tabla.setModel(prio.getModelo());
        }
        if (cmbOrden.getSelectedIndex() == 1){
            ModeloTablaFecha fecha = new ModeloTablaFecha(g.getTareas());
            tabla.setModel(fecha.getModelo());
        }
        if (cmbOrden.getSelectedIndex() == 2){
            ModeloTablaAlf alf = new ModeloTablaAlf(g.getTareas());
            tabla.setModel(alf.getModelo());
        }
    }//GEN-LAST:event_cmbOrdenActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new interfaz_lista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable tabla; // CAMBIADO: De JList a JTable
    // End of variables declaration//GEN-END:variables
}